package com.infotsav.test.Util;

import com.infotsav.test.R;

public class Constants {
    public static final String Home = "Home";
    public static final String Events = "Events";
    public static final String Register = "Register";
    public static final String Updates = "Updates";
    public static final String Contactus = "Contact Us";
    public static final String Aboutus = "About Us";
    public static final String Sponsors = "Sponsors";
    public static final String Treasurehunt = "Treasure Hunt";
    public static final String all="all";
    public static final String gamiacs="gamiacs";
    public static final String managerial="managerial";
    public static final String online="online";
    public static final String onsite="onsite";
    public static final String robotics="robotics";
    public static final String technical="technical";
    public static final String school="school";
    public static final int back1=R.drawable.b1;
    public static final int back2=R.drawable.b2;
    public static final int back3=R.drawable.b3;
    public static final int back4=R.drawable.b4;
    public static final int back5=R.drawable.b5;
    public static final int back6=R.drawable.b6;
    public static final int back7=R.drawable.b7;
    public static final int back8=R.drawable.b8;
    public static final int back9=R.drawable.b9;
    public static final int back10=R.drawable.b10;
    public static final int back11=R.drawable.b11;
    public static final int back12=R.drawable.b12;
    public static final String fact1="Marvel created a superhero named Throg. He is a frog that has the power of Thor and is in a group called the Pet Avengers";
    public static final String fact2="'Wakandan' Is Actually A Real South African Language, Xhosa";
    public static final String fact3="'Iron Man 2,' 'The Incredible Hulk,' And 'Thor' All Occur Within The Same Week";
    public static final String fact4="Chris Evans Turned Down The Role Of Captain America…Three Times!";
    public static final String fact5="Loki Is 1,053 Years Old";
    public static final String fact6="The MCU Has It's Own News Channel";
    public static final String fact7="The Original Avengers Lineup Included The Wasp";
    public static final String fact8="The Incredible Hulk is the shortest MCU movie";
    public static final String fact9="Jeremy Renner was trained by an Olympic Archer for the role of Hawkeye";
    public static final String fact10="Marvel Cinematic Universe is the highest grossing movie franchise of all time beating Star Wars by USD 8 billion";
    public static final String fact11="Captain Marvel was supposed to make an appearance in ‘Age of Ultron’, but it was scrapped";
    public static final String fact12="Bruce Banner was planned to turn into an angrier Grey Hulk under Scarlet Witch’s spell in ‘Age of Ultron’";
    public static final String fact13="It took 2 years to create the scene of dancing baby Groot in the beginning of ‘Guardians Of The Galaxy Vol.2’";
    public static final String fact14="Tom Holland found out he was playing Spider-Man on Instagram";
    public static final String fact15="Iron Man has the highest critic score and audience score combined average: 92.5%";
    public static final String fact16="Stan Lee Wanted To Play Odin";
    public static final String fact17="Vin Diesel Gets Special Groot Scripts That Reveal His Dialogue";
    public static final String fact18="Thanos Could Lift The Titanic";
    public static final String fact19="Gal Gadot Almost Played Nebula";
    public static final String fact20="Tony Stark Isn’t The Richest Avenger, Black panther is";
    public static final String fact21="The Marvel Cinematic Universe is the highest-grossing film franchise of all time";
    public static final String fact22="While Deadpool is a Marvel property, it is not (currently) part of the Marvel Cinematic Universe";
    public static int indexval=0;
}
